type User {
  id: ID!
  firstName: String
  lastName: String
  email: String
  image: String
  role: String
  createdAt: String
  updatedAt: String
  appointments: [Appointment!]
  notifications: [Notification!]
  comments: [Comment!]
  chat: [Chat!]
}

type Appointment {
  id: ID!
  name: String
  description: String
  color: String
  endDate: String
  startDate: String
  ownerId: Int
  approverId: Int
  isApproved: Boolean
  createdAt: String
  updatedAt: String
  owner: User!
  approver: User!
}

type Notification {
  id: ID!
  message: String
  link: String
  isSeen: Boolean
  userId: Int
  createdAt: String
  updatedAt: String
  user: User!
}

type Comment {
  id: ID!
  message: String
  appointmentId: Int
  userId: Int
  createdAt: String
  updatedAt: String
  appointment: Appointment!
  user: User!
}

type Chat {
  id: ID!
  message: String
  senderId: Int
  receiverId: Int
  createdAt: String
  updatedAt: String
  sender: User!
  receiver: User!
}

type Analytics {
  users: Int
  appointments: Int
  comments: Int
  bookings: Int
}

type Query {
  user(id: Int!): User
  users(offset: Int, limit: Int, orderBy: String, orderCol: String): [User]
  userSearch(keyword: String!): [User]
  login(email: String, password: String): String

  appointment(id: Int!): Appointment
  appointments(
    limit: Int
    offset: Int
    userId: Int
    orderBy: String
    orderCol: String
  ): [Appointment]

  notification(id: Int!): Notification
  notifications(
    limit: Int
    offset: Int
    userId: Int
    orderBy: String
    orderCol: String
  ): [Notification]

  comment(id: Int!): Comment
  comments(
    limit: Int
    offset: Int
    userId: Int
    orderBy: String
    orderCol: String
  ): [Comment]

  chat(id: Int!): Chat
  chats(
    limit: Int
    offset: Int
    userId: Int
    orderBy: String
    orderCol: String
  ): [Chat]

  analytics: Analytics
  printActivity(range: String!, userId: Int!): String
}

type Mutation {
  register(
    firstName: String!
    lastName: String!
    email: String!
    password: String!
  ): String

  deleteUser(id: Int!): String

  addAppointment(
    name: String!
    description: String
    startDate: String!
    endDate: String!
    color: String
    ownerId: Int!
    approverId: Int
    isApproved: Boolean
  ): Appointment

  updateAppointment(
    id: Int!
    name: String
    description: String
    startDate: String
    endDate: String
    color: String
    ownerId: Int
    approverId: Int
    isApproved: Boolean
  ): Appointment

  deleteAppointment(id: Int!): String

  updateNotification(
    id: Int!
    message: String
    link: String
    isSeen: Boolean
    userId: Int
  ): Notification

  addComment(message: String!, appointmentId: Int!, userId: Int!): Comment

  updateComment(
    id: Int!
    message: String
    appointmentId: Int
    userId: Int
  ): Comment

  deleteComment(id: Int!): String

  addChat(email: String!, message: String!, senderId: Int!): Chat

  deleteChat(id: Int!): String
}
